### ISSUE TITLE
Falta um ecrã de boas vindas para evitar erro na primeira submissão

### ISSUE THREAD

**Issue by waldyrious** [jfoclpf/in-my-district#1]
Instalei a app, e ao abri-la pela primeira vez apareceu logo o ecrã de enviar uma comunicação. Experimentei preencher os dados e carregar em "Gerar texto" para ver como ficava, e apareceu um erro a dizer que eu tinha que preencher os campos obrigatórios nome completo, número de identificação, etc.

Olhei novamente para o formulário e não vi nenhum desses campos. Só depois ao abrir o menu lateral percebi que esses campos pertenciam a um formulário diferente (na vista "Os meus dados").

Ao abrir a app pela primeira vez, eu esperaria ver um ecrã com um texto introdutório que explicasse como a app funciona, e a informar que seria necessário introduzir os meus dados antes de poder enviar comunicações. Aliás, nem sequer deveria ser possível ir para o ecrã de submissão antes de ter preenchido os dados.

**Comment by jfoclpf** [comment]
bem visto @waldyrious 

sugeres então que na primeira utilização da APP o utilizador seja reencaminhado diretamente para o campo do nome, morada, etc.?

**Comment by waldyrious** [comment]
Eu pensei inicialmente nisso, mas acho que pode ser um bocado agressivo começar logo a pedir dados pessoais mal se abre a aplicação. Acho que faz mais sentido ter um ecrã "home" que sirva não só para essa primeira utilização, mas até para o uso normal, como hub de navegação.

Podia ser algo simples, com o título em cima, logótipo, um parágrafo a explicar o que a app faz, um link para mais info, e dois botões para as duas ações principais: introdução/atualização dos dados pessoais, e comunicação de nova ocorrência (que estaria desativado inicialmente).

Depois até se podia acrescentar botões aí para funcionalidade adicional (p.ex. registo de comunicações já feitas, heatmap de comunicações, etc.)

**Comment by jfoclpf** [comment]
Olá @waldyrious 

é isso que eu não queria, começar logo a pedir dados pessoais. Sim, vou fazer isso, um popup inicial a explicar como funciona e que o utilizador tem de preencher os dados pessoais. Essa ideia dos botões nesse ecrã inicial parace-me excelente

> Depois até se podia acrescentar botões aí para funcionalidade adicional (p.ex. registo de comunicações já feitas, heatmap de comunicações, etc.)

Sim, já tenho isso em lista de espera, vê a [outra a APP](https://play.google.com/store/apps/details?id=com.form.parking.violation) que desenvolvi parecida, já faço isso, tem no menu um Histórico e um heatmap.

**Comment by waldyrious** [comment]
Wow, foste tu também que criaste essa? Muitos parabéns, estás a fazer um trabalho público de valor!

**Comment by jfoclpf** [comment]
> Wow, foste tu também que criaste essa? Muitos parabéns, estás a fazer um trabalho público de valor!

sim, fui eu :) muito obrigado

vou então fazer um ecrã de boas-vindas, parece-me bem, obrigado pelas sugestões

**Comment by jfoclpf** [comment]
já resolvi este problema, não coloquei um ecrã de boas vindas, mas quando o utilizador carrega no botão e faltam dados pessoais, informo sobre legislação aplicável e porque motivo devem preenchê-los.

**Comment by jfoclpf** [comment]
sairá na próxima versão

**Comment by jfoclpf** [comment]
Olá @waldyrious finalmente coloquei ecrã de boas-vindas com uma pequena nota explicativa.

**Comment by waldyrious** [comment]
Great! Tenho uma dúvida se não seria melhor linkar o "terá de se identificar" ao ecrã "Os meus dados", ou pelo menos dizer como se faz para ir lá ter.

De qualquer forma, já é muito bom haver uma introdução quando se abre a app! :+1:
