### ISSUE TITLE
Escolher na aplicação enviar para a junta, para a camâra ou para os dois

### ISSUE THREAD

**Issue by froque** [jfoclpf/in-my-district#11]
Na minha experiência quando se envia para todos, ninguém se sente dono do assunto. 

A minha ideia é uma checkbox ou radiobutton para escolher a quem enviar. 

Sei que dá para editar no email, mas a experiência de utilizador fica mais estranha.

**Comment by jfoclpf** [comment]
Bem visto, vou implementar mal arranje um tempinho

**Comment by jfoclpf** [comment]
@froque já está implementado, sairá na próxima versão para Android
