### ISSUE TITLE
Renomear o repo?

### ISSUE THREAD

**Issue by waldyrious** [jfoclpf/in-my-district#2]
É confuso a app chamar-se "No meu bairro" quando o nome do repositório é "in-my-district". Seria talvez benéfico renomear o repositório, e aproveitar enquanto ainda está nascente para o fazer :)

**Comment by jfoclpf** [comment]
obrigado pela dica @waldyrious 

A questão é que no longo prazo tenho planos para internacionalizar a APP :)
