### ISSUE TITLE
Colocar loading quando se clica em gerar texto

### ISSUE THREAD

**Issue by worm69** [jfoclpf/in-my-district#20]
Ontem enquanto testava carreguei varias vezes e submeti varias vezes um loading e bloquear o botão durante o processo evitava isso

Abraço

**Comment by jfoclpf** [comment]
Bem visto, vou implementar quando chegar a casa

**Comment by jfoclpf** [comment]
Boas @worm69 , já resolvi esta questão, com be882f0760079aec897c7951f88928dc6fba58eb

Deu um pouco mais de trabalho porque aquilo é tudo assíncrono e tive que criar uma série de promessas jQuery (`$.Deferred()`) para detectar exatamente quando a operação de envio de dados para a DB e envio para a APP de email tinha terminado. Usei os [spinners bootstrap](https://getbootstrap.com/docs/4.4/components/spinners/).

Acho que já está, testei agora em Android e parece estar a funcionar. Quando tiveres um tempinho para testar aí na versão iOS diz :)

Um grande abraço

**Comment by jfoclpf** [comment]
![Peek 2021-11-05 23-22](https://user-images.githubusercontent.com/3984909/140584990-a8048d2e-e18f-47d3-b377-eb1fa240efa9.gif)

**Comment by jfoclpf** [comment]
Olá @worm69 vou fechar este assunto porque acho que ficou resolvido, se entretanto encontrares algum bug nesta implementação, posso reabrir.
um abraço
