### ISSUE TITLE
Possibilitar uso de clientes de email não-google

### ISSUE THREAD

**Issue by a-silvia** [jfoclpf/in-my-district#28]
Olá! Primeiro, desculpem se isto está relacionado com o [#22](https://github.com/jfoclpf/in-my-district/issues/22). Quero poder usar outro cliente de email para enviar os emails; em telemóveis que não tenham o gmail instalado por exemplo isto seria muito útil.

Obrigada!

**Comment by jfoclpf** [comment]
Isso já é possível, pela menos com Outlook mail. Que clientes estamos a falar?

**Comment by a-silvia** [comment]
O que eu uso é o K9. Num telemóvel com gmail não tive opção senão gmail; num que está "de-googled" fica em infinite loop! Obrigada!

**Comment by jfoclpf** [comment]
Olá @a-silvia compreendo a frustração, mas há pouco que possa fazer, limito-me a usar o plugin de email do Cordova
https://github.com/katzer/cordova-plugin-email-composer

**Comment by a-silvia** [comment]
Ah OK, percebo. Obrigada e parabéns pelo projecto (já me vieram arranjar um problema na rua graças à app)!

**Comment by jfoclpf** [comment]
> Obrigada e parabéns pelo projecto (já me vieram arranjar um problema na rua graças à app)!

A sério! Boa! Fico muito feliz por sabê-lo! Como fizeste? Que app de email usaste então?

**Comment by a-silvia** [comment]
Eu tenho o gmail no telemóvel pq (ainda não) de-google. Portanto foi directo!

Estava a pensar, achas q faz sentido dar a hipótese só de mostrar o texto e os emails na aplicação? Depois posso manualmente passar para o meu cliente de email!

**Comment by jfoclpf** [comment]
Dar o texto não seria problema, o problema seria depois lidar com os anexos até porque a app gera um anexo com um imagem de um mapa, por exemplo

**Comment by a-silvia** [comment]
Pois, o email não fica tão bem. A foto dá para anexar à mão mas o mapa já não é tão directo.

Mas se no passo em que se gera o texto mostrasse também os emails destinatários, assim sempre dava para mandar qq coisa. Se desse para acrescentar isso, pessoas sem gmail têm de fazer alguns passos à mão mas chegam lá. Faz sentido?

**Comment by jfoclpf** [comment]
Faz de facto sentido, o problema é que depois as fotos das ocorrências não iriam para a base de dados para serem partilhadas com todos e com o mapa de ocorrências que é público, e o registro na base de dados não teria informações visuais, o que seria uma grande lacuna.

Repara que a base de dados recolhe apenas dados anónimos da ocorrência, jamais recolhe dados pessoais.
