### ISSUE TITLE
Criar um credentials-sample.json 

### ISSUE THREAD

**Issue by enieber** [jfoclpf/in-my-district#29]
Olá, recentemente conheci o projeto e gostei da proposta, seria interessante ter um arquivo de exemplo de como configurar o servidor. Algo coomo um credentials-sample.json com valore ficticions.

**Comment by enieber** [comment]
um outra alternative seria usar .env ao inves de um json

**Comment by jfoclpf** [comment]
Bem visto, vou adicionar, eu de facto tenho as credenciais da base de dados apenas no meu PC.

**Comment by enieber** [comment]
foi uma boa não compartilhar  as envs..

**Comment by jfoclpf** [comment]
Olá @enieber estou a tratar disso
Não são env, são mesmo uma série de ficheiros que estou a agrupar numa pasta `/keys/`
Estou a agrupá-los todos nesta pasta e em breve forneço uns samples dentro desta pasta para que possam ser replicadas.
Foi bem visto porque estavam algo dispersos.

Há quatro ficheiros:
 - a chave para assinar as APPs (por exemplo para a Play Store), para gerar uma chave [correr](https://stackoverflow.com/questions/3997748/how-can-i-create-a-keystore):
```
keytool -genkey -v -keystore my-release-key.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000
```
 - a password para essa chave, que é usada nos BASH scripts em `/scripts` (por exemplo [aqui](https://github.com/jfoclpf/in-my-district/blob/main/scripts/buildReleaseAAB.sh#L11))
 - credenciais para o código Javascript da APP, como por exemplo o UUID dos smartphones dos administradores
 - credenciais para o código do servidor, como por exemplo as credenciais da Base de Dados

**Comment by jfoclpf** [comment]
Feito, estava tudo um pouco disperso, mas agora está tudo arranadinho aqui
https://github.com/jfoclpf/in-my-district/tree/main/keys
