### ISSUE TITLE
Mapa não tem atribuição

### ISSUE THREAD

**Issue by waldyrious** [jfoclpf/in-my-district#30]
Tanto quanto posso aferir, o mapa em https://nomeubairro.app/mapa/ usa dados (e imagens) do OpenStreetMap, mas não está visível a atribuição, como é requerido em https://wiki.openstreetmap.org/wiki/Community_attribution_advice#Interactive_maps.

Se for preciso mais informação sobre como efetivar essa indicação, a [comunidade OSM Portugal](https://t.me/osmportugal) pode ajudar.

**Comment by jfoclpf** [comment]
Bem visto, isso é importante, vou fazer

**Comment by jfoclpf** [comment]
feito

**Comment by waldyrious** [comment]
Nice! Já agora, por curiosidade, os commits deste repositório não estão sincronizados com o que está live no site?

**Comment by jfoclpf** [comment]
Bem visto :)

É um site WordPress à parte, não sei bem como colocar um site WordPress num GitHub, teria que investigar

**Comment by jfoclpf** [comment]
> Nice! Já agora, por curiosidade, os commits deste repositório não estão sincronizados com o que está live no site?

Após uma manhã - não foi fácil, porque o wordpress não é facilmente sincronizável com um git - já está

https://github.com/jfoclpf/in-my-district/tree/main/wordpress-website

**Comment by waldyrious** [comment]
És uma máquina, pá!

Btw, link atualizado, para referência futura: https://github.com/jfoclpf/in-my-district/tree/main/website
