### ISSUE TITLE
Hotlinks para ocorrências específicas

### ISSUE THREAD

**Issue by waldyrious** [jfoclpf/in-my-district#31]
Era interessante haver a possibilidade de se linkar diretamente para uma ocorrência. Podia ser no [mapa](https://nomeubairro.app/mapa/), ou numa página com uma listagem separada, se for mais prático.

**Comment by jfoclpf** [comment]
Obrigado pelas sugestões @waldyrious 

Referes-te a um URL por cada ocorrência?
Com as infos que aparecem já no mapa?

É bem visto.

**Comment by waldyrious** [comment]
Sim, porque isso permitiria fazer bookmark de ocorrências, partilhar, etc.

**Comment by jfoclpf** [comment]
Bem visto, tenho apenas que criar um URL com o UUID da ocorrência, não deve ser difícil

**Comment by jfoclpf** [comment]
Já está, obrigado pelas dicas, continua :) 

Um dia a programar e aqui vai

exemplos:
https://nomeubairro.app/ocorrencia/?uuid=35a01022-3568-48ad-8041-e1b7d98a26b3
https://nomeubairro.app/ocorrencia/?uuid=10a4b6f2-2fc3-40d2-aa8f-e0cfaa9b83a1

Os hotlinks estão todos disponíveis no mapa
https://nomeubairro.app/mapa/

**Comment by waldyrious** [comment]
Muito fixe! :clap: Vou já usar um link desses para reportar um problema com uma ocorrência :D
