### ISSUE TITLE
Filtrar mapa de anomalias por estado de resolução

### ISSUE THREAD

**Issue by waldyrious** [jfoclpf/in-my-district#32]
No [mapa](https://nomeubairro.app/mapa/) pode-se ver a indicação de quantas anomalias estão resolvidas, e quantas estão por resolver. Era interessante haver uma forma de as filtrar no mapa, semelhante ao menu dropdown que já existe para o tipo de anomalia.

**Comment by jfoclpf** [comment]
Olá @waldyrious esta questão já não se coloca porque agora mostro apenas as ocorrências por resolver
Acho que não vale a pena mostrar tudo o que ficou para trás porque pode crescer exponencialmente

Pedia-te contudo que nos ajudasses a decidir a questão #19 

agradecido
