### ISSUE TITLE
Remover restrição geográfica para instalação

### ISSUE THREAD

**Issue by waldyrious** [jfoclpf/in-my-district#33]
A minha conta Google não está associada a Portugal, e por causa disso (penso eu) na Play Store não consigo instalar a app: aparece-me o texto "This app is not available for your device".

Isto já me aconteceu com outras apps semelhantes, que são específicas para utilizadores de Portugal. Infelizmente isso faz com que eu não possa usar a app e reportar ocorrências. Seria possível levantar essa restrição e permitir a qualquer pessoa instalar a app?

**Comment by jfoclpf** [comment]
Olá, eu coloco essa restrição porque é super frustrante ter pessoas que descarregam por engano e depois como não funciona levo com nota 1 na Play Store.

Eu posso levantar a restrição para o teu país. A tua conta está registrada em que país?

**Comment by waldyrious** [comment]
Deixa estar, está associada aos Estados Unidos :sweat_smile: eu descobri entretanto que [posso alterar o país uma vez por ano](https://support.google.com/googleplay/answer/7431675?hl=en), por isso vou fazer a alteração para Portugal. Se depois voltar a precisar de a associar aos EUA, devo conseguir repor como estava. Obrigado pela resposta rápida!
