### ISSUE TITLE
Imagem em falta em três ocorrências

### ISSUE THREAD

**Issue by waldyrious** [jfoclpf/in-my-district#34]
Estas três ocorrências, todas na mesma rua e reportadas em sequência, têm imagens em falta:

- https://nomeubairro.app/ocorrencia/?uuid=66144faa-f516-4779-b5a5-5de4b889bce3
- https://nomeubairro.app/ocorrencia/?uuid=ecfc6a8e-57e5-4bcc-b115-3495a16c3621
- https://nomeubairro.app/ocorrencia/?uuid=c937ef91-07d4-48e6-a0fd-db57d29da784

**Comment by jfoclpf** [comment]
Agradecido @waldyrious , já está resolvido com 6706f6c5c92f1bddf9b17360cb616e90e5f2cd73

Eu tinha um script que fazia uma limpeza periódica à tabela da DB, mas apenas eliminava da tabela as entradas onde todas as fotos eram inexistentes, mas não apagava (emendava para `''`) fotos individuais, caso outras fotos existissem para a mesma entrada.

Já está, qualquer erro ou sugestão adicionais, por favor avisa aqui no github :)

**Comment by waldyrious** [comment]
Yeah, fantástico! Obrigado pela correção :)

**Comment by jfoclpf** [comment]
Eu é que agradeço :) se encontrares outros ou tiveres mais sugestões erros avisa
