### ISSUE TITLE
Typo no email. 

### ISSUE THREAD

**Issue by goncard** [jfoclpf/in-my-district#41]
Encontrei um typo no email gerado. "Datectada" em vez de "Detectada". 

![IMG_20220626_140022](https://user-images.githubusercontent.com/45340597/175815373-f5f5faa1-d935-400b-b764-4b836563e8a3.jpg)

**Comment by jfoclpf** [comment]
Muito obrigado, será corrigido na próxima versão

**Comment by jfoclpf** [comment]
resolvido, sairá amanhã ou depois de amanhã quando o play store atualizar, já foi enviado para a play store, agradecido
