### ISSUE TITLE
Ilhas!

### ISSUE THREAD

**Issue by surajerama** [jfoclpf/in-my-district#47]
O mapa não permite visualizar ocorrências nas ilhas dos Açores e Madeira..

**Comment by jfoclpf** [comment]
Refere-se a qual mapa?

A este?

https://nomeubairro.app/mapa/

Verdade, vou corrigir ASAP

**Comment by jfoclpf** [comment]
@surajerama 
Já está, foi só alterar os limites do mapa para

`L.latLngBounds(L.latLng(31.256835, -34.386606), L.latLng(45.758661, -3.583837))`

**Comment by jfoclpf** [comment]
Resolvido aqui:

https://github.com/jfoclpf/in-my-district/commit/872b2f1fc4f9d6ba9b11244cf8bc4e11fa6e9092#r81155315

**Comment by surajerama** [comment]
Dei o feedback sem testar, sorry. Vivo nos Açores e dá erro no mapa, não apresenta as ilhas ainda.

**Comment by jfoclpf** [comment]
Mas referes-te a este mapa?

https://nomeubairro.app/mapa/
