### ISSUE TITLE
Atualizar APP no F-Droid

### ISSUE THREAD

**Issue by RavingSombra** [jfoclpf/in-my-district#48]
Hoje procurei usar a app para reportar uma anomalia e deparei-me com este erro
![Screenshot_20221024-123518](https://res.cloudinary.com/djditx2nm/image/upload/c_scale,q_100,w_320/v1666642492/Screenshot_20221024-123518_tudpad.png)

Apesar do GPS funcionar corretamente e preencher o campo da rua, continuo com as opções de concelho e freguesia bloqueadas.
Estou a usar um Pixel 3XL com CalyxOS no Android 12. App instalada pela F-Droid.

Há 1-2 meses não tive quaisquer problemas quando precisei de usar a app para reportar uma anomalia.

**Comment by jfoclpf** [comment]
Estranho, a APP faz uso deste serviço para obter o município e freguesia: https://geoapi.pt/

Pode ser que tenha estado em baixo temporariamente, mas testei agora do meu lado e funcionou

pode verificar novamente sff?

**Comment by jfoclpf** [comment]
obrigado pela informação,  de facto não percebo por que motivo não funciona na playstore

**Comment by jfoclpf** [comment]
@RavingSombra reparei agora que usas a APP no F-Droid. O F-Droid ficou para trás nas atualizações devido a uma mudança da estrutura desta repo.

Vou ver isso agora e já digo algo

**Comment by jfoclpf** [comment]
Já foi feito o pedido
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9528

**Comment by jfoclpf** [comment]
PR request feito ao F-Droid: 
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12450

**Comment by RavingSombra** [comment]
Agradeço a atenção :D quando conseguir instalar a versão atual pela F-Droid dou feedback

**Comment by RavingSombra** [comment]
Recebi hoje a atualização, tudo a funcionar como esperado
