### ISSUE TITLE
Anexar fotos nos lembretes

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/in-my-district#53]
No Histórico quando se enviam lembretes, a APP não está a anexar as fotos correctamente à mensagem de email.

Fazer o download das fotos como dataURL, até porque será compatível também com iOS (@worm69 )

https://stackoverflow.com/a/75244388/1243247

**Comment by worm69** [comment]
Domingo já testo em iOS e deixo feedback

**Comment by jfoclpf** [comment]
Muito obrigado Daniel

Entretanto vou fechar o issue porque este em particular está resolvido
