### ISSUE TITLE
Android 13 camera plugin issue

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/in-my-district#54]
https://github.com/apache/cordova-plugin-camera/issues/797

devo tentar instalar o plugin usando um PR que endereça esta questão

```
cordova plugin add https://github.com/apache/cordova-plugin-camera.git#pull/814/master
```

**Comment by jfoclpf** [comment]
No config xml deve estar

```
<preference name="android-compileSdkVersion" value="33"/>
```

**Comment by jfoclpf** [comment]
solved

**Comment by Marwanb10** [comment]
Hi jfoclpf
i have probleme when i get permission from device to access i give him access to open camera but not open i think reply i get error probleme in permission make camera doesn't open 
in console.log i get error 20 
i use angular 9 and ionic 5.4.16
