### ISSUE TITLE
ajuda individual e coletiva 

### ISSUE THREAD

**Issue by ghost** [jfoclpf/in-my-district#60]

**Comment by jfoclpf** [comment]
quer ajudar? ótimo 

sabe programar em Java script?

**Comment by jfoclpf** [comment]
Obrigado @lucasnuic muito obrigado pela disponibilidade

Neste momento gostava de tentar resolver esta questão, acha que consegue ajudar?
https://github.com/jfoclpf/in-my-district/issues/40
