### ISSUE TITLE
App não permite o preenchimento de nova ocorrência devido a problemas com localização

### ISSUE THREAD

**Issue by nafarinha** [jfoclpf/in-my-district#61]
Em dois Android diferentes (versões Android 15 e Android 13), instalei a versão disponível no F-Droid ( 1.3.3) e em ambos os equipamentos, ao fim de algum tempo após abrir a app, surge o erro "Erro na obtenção do local da ocorrência!". Mesmo com a localização ativa e autorizada, a app dá este erro constantemente. Há alguma razão para a app exigir obrigatoriamente a localização automática para poder ser utilizada? No meu caso, quero criar uma ocorrência para um local onde não estou fisicamente. Seria preferível que o utilizador pudesse manualmente selecionar o município e freguesia, algo que a app não permite quando se tenta selecionar os campos de preenchimento.

**Comment by jfoclpf** [comment]
Olá, no mapa podes arrastar o ponto para o local pretendido, não precisa de
ser o local onde estás, mas precisas de dar autorização de internet e GPS.

**Comment by nafarinha** [comment]
Olá João,
Não tenho nenhum mapa disponível. Quer o campo de Concelho, quer o de Freguesia não permitem o preenchimento manual. Em ambos os equipamentos, o que tenho é o que está na imagem abaixo, isto é antes da mensagem de erro mencionada inicialmente.
![Screenshot_20241030-225612_No meu Bairro!](https://github.com/user-attachments/assets/7639f30c-a554-4662-a067-ee60e08166e7)

Fyi, tenho também instalada a tua outra app de Denúncia de Estacionamento. O formulário nesta app funciona, posso preencher o campo Concelho e Freguesia. Menciono isto pois, pelo menos visualmente, ambas as apps parecem usar um formulário semelhante. Estou a usar a versão do F-Droid, posso assumir que a app deveria funcionar sem os serviços Google? Ou o Maps API e o GMS em geral é um pré-requisito, mesmo para a versão F-Droid? 

edit: a app tem permissões para internet e gps.

**Comment by jfoclpf** [comment]
Estranho, isso parece um problema de acesso à Internet. Tens a certeza que a APP tem permissão de acesso à Internet? 

Eu vejo assim do meu lado:

Experimenta também instalar via Play Store, para ver se há algum problema com a versão do F-droid

![Screenshot_2024-10-31-09-54-20-611_com.in.my.district.jpg](https://github.com/user-attachments/assets/a61a8d0d-9e04-409b-8fda-945943e56064)

**Comment by nafarinha** [comment]
Olá João, não há nenhum problema de acesso à internet e como referi o formulário da outra app, Denúncia Estacionamento, funciona, apesar de não mostrar o mapa. O browser, outras app não têm qualquer problema de acesso à Internet; não tenho nenhuma firewall ou VPN ativos que pudessem interferir com o acesso da app à Internet. A versão Play Store tem o mesmo problema em ambos os equipamentos.

**Comment by jfoclpf** [comment]
Havia um problema com o servidor de geolocalização.

Podes experimentar novamente com a APP da Play Store?

**Comment by nafarinha** [comment]
Infelizmente tudo na mesma. A app está com permissão de GPS não existe nada a impedir o acesso à Internet. Logo depois do teste abaixo, abrir sem problemas o Google Maps. Se existisse uma forma de poder preencher os campos de concelho e freguesia manualmente (tal como acontece com a app Denúncia Estacionamento), mesmo com o problema original, seria possível continuar com o preenchimento do formulário.
![Screenshot_20241113-222050](https://github.com/user-attachments/assets/1d838104-1b07-4264-aa41-964ad00d0fcd)
![Screenshot_20241113-222055](https://github.com/user-attachments/assets/b21043eb-9adc-4a55-b39a-e71ff477131c)
![Screenshot_20241113-223101](https://github.com/user-attachments/assets/07fa2c9c-4f8b-4fdc-a13b-4de636df03fb)

**Comment by jfoclpf** [comment]
Olá, estive a programar, pode confirmar que ficou resolvido este problema?

**Comment by nafarinha** [comment]
Olá João. Já funciona :) Apenas um detalhe: na lista de municípios 'Mação' surge depois de 'Matosinhos', quando deveria estar a seguir de 'Lousã', provavelmente a ordenação da lista está a ignorar os caracteres especiais do português. Obrigado e abc
